package com.treeeducation.ioas.applicationflow;

public enum ApplicationAttachmentType {
    PASSPORT,
    ID_CARD,
    TRANSCRIPT,
    DIPLOMA,
    LANGUAGE_SCORE,
    RESUME,
    PERSONAL_STATEMENT,
    RECOMMENDATION_LETTER,
    WORK_EXPERIENCE,
    FINANCIAL_PROOF,
    SCHOOL_APPLICATION_FORM,
    OFFER_LETTER,
    VISA_APPLICATION_FORM,
    VISA_PAYMENT_RECEIPT,
    MEDICAL_CHECK,
    BIOMETRIC_APPOINTMENT,
    VISA_RESULT,
    FLIGHT_TICKET,
    ACCOMMODATION,
    OTHER
}
