package com.treeeducation.ioas.media.contentpackage;
import com.treeeducation.ioas.audit.*;import com.treeeducation.ioas.auth.UserPrincipal;import com.treeeducation.ioas.common.BusinessException;import com.treeeducation.ioas.media.assetfile.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;
/** Application service for media topic packages. */
@Service public class ContentPackageService{ private final ContentPackageRepository repo; private final AssetFileRepository files; private final AuditLogRepository audits; public ContentPackageService(ContentPackageRepository repo,AssetFileRepository files,AuditLogRepository audits){this.repo=repo;this.files=files;this.audits=audits;}
 @Transactional public ContentPackage create(ContentPackageDtos.UpsertRequest r,UserPrincipal p){ContentPackage cp=new ContentPackage(); cp.setName(r.name());cp.setDescription(r.description());cp.setStatus(r.status()==null?ContentPackageStatus.draft:r.status());cp.setCreatedBy(p.id());cp=repo.save(cp); audit(AuditAction.create_package,"content_package",cp.getId(),p.id(),cp.getName());return cp;}
 public Page<ContentPackageDtos.Response> list(Pageable pageable){return repo.findAll(pageable).map(ContentPackageDtos::of);} public ContentPackage get(Long id){return repo.findById(id).orElseThrow(()->BusinessException.notFound("主题包不存在"));}
 @Transactional public ContentPackage update(Long id,ContentPackageDtos.UpsertRequest r){ContentPackage cp=get(id);cp.setName(r.name());cp.setDescription(r.description());if(r.status()!=null)cp.setStatus(r.status());cp.setUpdatedAt(Instant.now());return cp;}
 @Transactional public void delete(Long id){ContentPackage cp=get(id); if(!files.findByPackageIdAndIsDeletedFalse(id).isEmpty()) throw BusinessException.badRequest("主题包仍包含文件，不能删除"); repo.delete(cp);} @Transactional public void refreshCounts(Long id){ContentPackage cp=get(id);var list=files.findByPackageIdAndIsDeletedFalse(id);cp.setScriptCount((int)list.stream().filter(f->f.getType()==AssetFileType.script).count());cp.setVideoCount((int)list.stream().filter(f->f.getType()==AssetFileType.video).count());cp.setImageCount((int)list.stream().filter(f->f.getType()==AssetFileType.image).count());}
 private void audit(AuditAction a,String t,Long tid,Long actor,String d){AuditLog log=new AuditLog();log.setAction(a);log.setTargetType(t);log.setTargetId(tid);log.setActorId(actor);log.setDetail(d);audits.save(log);} }
