package com.treeeducation.ioas.media.assetfile;
import com.treeeducation.ioas.audit.*;import com.treeeducation.ioas.auth.UserPrincipal;import com.treeeducation.ioas.common.BusinessException;import com.treeeducation.ioas.media.contentpackage.*;import com.treeeducation.ioas.storage.*;import org.springframework.core.io.InputStreamResource;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import java.time.Instant;import java.time.temporal.ChronoUnit;
/** Application service enforcing file-package linkage and recycle-bin semantics. */
@Service public class AssetFileService{ private final AssetFileRepository repo; private final ContentPackageRepository packages; private final ContentPackageService packageService; private final ObjectStorageService storage; private final AuditLogRepository audits; public AssetFileService(AssetFileRepository repo,ContentPackageRepository packages,ContentPackageService packageService,ObjectStorageService storage,AuditLogRepository audits){this.repo=repo;this.packages=packages;this.packageService=packageService;this.storage=storage;this.audits=audits;}
 @Transactional public AssetFile upload(Long packageId,AssetFileType type,String description,MultipartFile file,UserPrincipal p){packages.findById(packageId).orElseThrow(()->BusinessException.notFound("主题包不存在")); if(file.isEmpty()) throw BusinessException.badRequest("文件不能为空"); StoredObject so=storage.put(packageId,file); AssetFile af=new AssetFile();af.setPackageId(packageId);af.setType(type);af.setDescription(description);af.setOriginalName(file.getOriginalFilename()==null?"file":file.getOriginalFilename());af.setMimeType(file.getContentType()==null?"application/octet-stream":file.getContentType());af.setFileSize(file.getSize());af.setBucketName(so.bucketName());af.setObjectKey(so.objectKey());af.setPreviewUrl(so.previewUrl());af.setThumbnailUrl(so.thumbnailUrl());af.setUploadedBy(p.id());af=repo.save(af);packageService.refreshCounts(packageId);audit(AuditAction.upload_asset,"asset_file",af.getId(),p.id(),af.getOriginalName());return af;}
 public Page<AssetFileDtos.Response> list(Long packageId,AssetFileType type,Pageable pageable){ if(packageId!=null) return repo.findByPackageIdAndIsDeletedFalse(packageId,pageable).map(AssetFileDtos::of); if(type!=null)return repo.findByTypeAndIsDeletedFalse(type,pageable).map(AssetFileDtos::of); return repo.findByIsDeletedFalse(pageable).map(AssetFileDtos::of);} public AssetFile get(Long id){return repo.findById(id).orElseThrow(()->BusinessException.notFound("文件不存在"));}
 @Transactional public void softDelete(Long id,UserPrincipal p){AssetFile f=get(id);f.setIsDeleted(true);f.setDeletedAt(Instant.now());f.setDeletedBy(p.id());f.setPurgeAt(Instant.now().plus(7,ChronoUnit.DAYS));packageService.refreshCounts(f.getPackageId());audit(AuditAction.delete_asset,"asset_file",id,p.id(),f.getOriginalName());}
 @Transactional public AssetFile restore(Long id,UserPrincipal p){AssetFile f=get(id);f.setIsDeleted(false);f.setDeletedAt(null);f.setDeletedBy(null);f.setPurgeAt(null);packageService.refreshCounts(f.getPackageId());audit(AuditAction.restore_asset,"asset_file",id,p.id(),f.getOriginalName());return f;} @Transactional public void purge(Long id,UserPrincipal p){AssetFile f=get(id);storage.remove(f.getObjectKey());repo.delete(f);packageService.refreshCounts(f.getPackageId());audit(AuditAction.purge_asset,"asset_file",id,p.id(),f.getOriginalName());}
 public Page<AssetFileDtos.Response> recycleBin(Pageable pageable){return repo.findByIsDeletedTrue(pageable).map(AssetFileDtos::of);} public ResponseEntity<InputStreamResource> download(Long id){AssetFile f=get(id);return ResponseEntity.ok().contentType(MediaType.parseMediaType(f.getMimeType())).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+f.getOriginalName()+"\"").body(new InputStreamResource(storage.get(f.getObjectKey())));} private void audit(AuditAction a,String t,Long tid,Long actor,String d){AuditLog log=new AuditLog();log.setAction(a);log.setTargetType(t);log.setTargetId(tid);log.setActorId(actor);log.setDetail(d);audits.save(log);} }
