package com.treeeducation.ioas.storage;
import io.minio.*;import io.minio.errors.*;import org.springframework.boot.context.properties.EnableConfigurationProperties;import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;import java.io.InputStream;import java.io.IOException;import java.security.InvalidKeyException;import java.security.NoSuchAlgorithmException;import java.util.UUID;
/** MinIO implementation; keep interface compatible with future OSS provider. */
@Service @EnableConfigurationProperties(StorageProperties.class) public class MinioObjectStorageService implements ObjectStorageService{ private final StorageProperties props; private final MinioClient client; public MinioObjectStorageService(StorageProperties props){this.props=props;this.client=MinioClient.builder().endpoint(props.endpoint()).credentials(props.accessKey(),props.secretKey()).build();}
 public StoredObject put(Long packageId, MultipartFile file){ try{ ensureBucket(); String original=file.getOriginalFilename()==null?"file":file.getOriginalFilename(); String key="packages/"+packageId+"/"+UUID.randomUUID()+"-"+original; client.putObject(PutObjectArgs.builder().bucket(props.bucket()).object(key).stream(file.getInputStream(),file.getSize(),-1).contentType(file.getContentType()).build()); String url=props.publicBaseUrl()+"/"+key; return new StoredObject(props.bucket(),key,url,url);}catch(Exception e){throw new IllegalStateException("对象存储写入失败",e);} }
 public InputStream get(String objectKey){ try{return client.getObject(GetObjectArgs.builder().bucket(props.bucket()).object(objectKey).build());}catch(Exception e){throw new IllegalStateException("对象存储读取失败",e);} }
 public void remove(String objectKey){ try{client.removeObject(RemoveObjectArgs.builder().bucket(props.bucket()).object(objectKey).build());}catch(Exception e){throw new IllegalStateException("对象存储删除失败",e);} }
 public String bucket(){return props.bucket();}
 private void ensureBucket() throws ServerException, InsufficientDataException, ErrorResponseException, IOException, NoSuchAlgorithmException, InvalidKeyException, InvalidResponseException, XmlParserException, InternalException { boolean exists=client.bucketExists(BucketExistsArgs.builder().bucket(props.bucket()).build()); if(!exists) client.makeBucket(MakeBucketArgs.builder().bucket(props.bucket()).build()); }
}
