CREATE TABLE IF NOT EXISTS data_recognition_records (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NULL,
    platform VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    scene VARCHAR(64) NOT NULL DEFAULT 'CONTENT_DETAIL',
    content_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
    account_name VARCHAR(255) NULL,
    account_id VARCHAR(128) NULL,
    content_title VARCHAR(512) NULL,
    confidence DECIMAL(8,4) NULL,
    raw_text LONGTEXT NULL,
    result_json LONGTEXT NULL,
    metrics_json LONGTEXT NULL,
    image_text_stats_json LONGTEXT NULL,
    video_stats_json LONGTEXT NULL,
    key_value_metrics_json LONGTEXT NULL,
    corrected_result_json LONGTEXT NULL,
    review_remark VARCHAR(1024) NULL,
    reviewed_by VARCHAR(128) NULL,
    reviewed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_data_recognition_records_request_id (request_id),
    KEY idx_data_recognition_records_status_created_at (status, created_at),
    KEY idx_data_recognition_records_content_type_created_at (content_type, created_at),
    KEY idx_data_recognition_records_platform_created_at (platform, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
