CREATE TABLE IF NOT EXISTS data_operation_purge_job (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    purge_no VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    preview_json LONGTEXT NULL,
    total_db_rows INT DEFAULT 0,
    total_objects INT DEFAULT 0,
    deleted_db_rows INT DEFAULT 0,
    deleted_objects INT DEFAULT 0,
    failed_objects INT DEFAULT 0,
    reason VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_by_name VARCHAR(100) NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    error_message LONGTEXT NULL,
    created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_data_operation_purge_job_no (purge_no),
    KEY idx_data_operation_purge_job_status (status),
    KEY idx_data_operation_purge_job_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_operation_purge_object (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    purge_job_id BIGINT NOT NULL,
    asset_id BIGINT NULL,
    bucket_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    public_url VARCHAR(1000) NULL,
    file_size BIGINT DEFAULT 0,
    delete_status VARCHAR(32) DEFAULT 'PENDING',
    error_message LONGTEXT NULL,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_data_operation_purge_object_job (purge_job_id),
    KEY idx_data_operation_purge_object_status (delete_status),
    CONSTRAINT fk_data_operation_purge_object_job FOREIGN KEY (purge_job_id) REFERENCES data_operation_purge_job(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
