CREATE TABLE IF NOT EXISTS data_recognition_records (
  id BIGINT NOT NULL AUTO_INCREMENT,
  request_id VARCHAR(64) NULL,
  platform VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  scene VARCHAR(64) NOT NULL DEFAULT 'CONTENT_DETAIL',
  content_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  account_name VARCHAR(255) NULL,
  account_id VARCHAR(128) NULL,
  content_title VARCHAR(512) NULL,
  confidence DECIMAL(8, 4) NULL,
  raw_text LONGTEXT NULL,
  result_json LONGTEXT NULL,
  metrics_json LONGTEXT NULL,
  image_text_stats_json LONGTEXT NULL,
  video_stats_json LONGTEXT NULL,
  key_value_metrics_json LONGTEXT NULL,
  corrected_result_json LONGTEXT NULL,
  review_remark VARCHAR(1024) NULL,
  reviewed_by VARCHAR(128) NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_data_recognition_status_created (status, created_at),
  KEY idx_data_recognition_content_type_created (content_type, created_at),
  KEY idx_data_recognition_platform_created (platform, created_at),
  KEY idx_data_recognition_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
